# Task:1

marks = int(input("Enter your marks :"))

if marks > 90:
    print("Excellent")

if marks > 80:
    print("Good")

if marks > 50:
    print("Moderate")

else:
    print("Fail")

# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ItfB8L6u2LhwhGneVMIiqBk6S_sL_IY0
"""

# While loop

i = 1

while i == 1:
  print(i)

  i = i + 1

# For Loop {Iterative}
# Range [start,stop,step]

for i in range(0,20,2):
  print(i)

for i in range(0,21):
  if i % 2 == 1:
    print(i)

for i in range(0,21):
  if i % 2 == 0:
    print(i)

# String Data types along with list

str = ["hello","World","Python Programming"]

for i in str:
  print(i)

str = ("hello","World","Python Programming")

for i in str:
  print(i)

name = "India"

print(type(name))

'''
note: when any function is defined a class it is called
"method of respective class"
'''

# Methods of strings (function de)

print(name.capitalize())   #camel casing
print(name.casefold())
print(name.lower())        #camel casing
print(name.upper())        #camel casing



name = [1,33,2,3,6]

# sorting is applicable for numbers and not for alphabets

name.reverse()
print(name)
name.sort()
print(name)
#----------------------------

student = ["kuldeep","mayur","sanskruti","valmik"]

for index, student in enumerate(student):
  print(f"index : {index} ,name :{student}")















