# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VDYHYMiar3KC92l_eG_bK0J7eQJfVDdN
"""

# pandas

import pandas as pd
import numpy as np

# create 1D array using Series()
a = pd.Series([1,2,3])
a

# create 1D array using Series()
a = pd.Series([1,2,3],index = ("a","b","c"))
a

# create 2D array using DataFrame()

a = pd.DataFrame([1,2,3,4,5,6],columns= ['value'],index = ['a','b','c','d','e','f'])
a

data = pd.DataFrame({'India':[10,20,30,40],
                    'USA': [40,50,60,70],
                    'UK': [100,200,300,400]})
data

# Concept of indexing
# using descriptive stats to calculate the data
data['India'].sum(),data['India'].mean(),data['India'].median(),data['India'].max(),data['India'].min()

# calculate IQR and also Q1 and Q3 for column India

Q1 = data['India'].quantile(0.25)
Q3 = data['India'].quantile(0.75)

IQR = Q3 - Q1

UW = Q3 + 1.5*IQR
LW = Q1 - 1.5*IQR

print(Q1,Q3,IQR,UW,LW)

# calculate skewness and kurtosis

skewness_India = data['India'].skew()
skewness_India

kurtosis_India = data['India'].kurt()
kurtosis_India

import matplotlib.pyplot as plt
data['India'].plot(kind = 'kde')
plt.axvline(25,color = 'r', linestyle = '--')
plt.axvline(32.5,color = 'g', linestyle = '--')
plt.axvline(17.5,color = 'g', linestyle = '--')
plt.axhline(0.005,color = 'b',linestyle = '--')
plt.show()

# .head() provides required rows from top
data.head(3)

# .tail provides required rows from bottom
data.tail(3)

# data gets shuffeled ::: 1 means 100% suffle
data.sample(frac = 1)

# checking dataset information and description stats
'''
data.info(): guides us following parameters
1.no of rows
2.no.of colums
3.datatype of each column
'''
data.info()

# derives desciptive stats
data.describe()

# chaecking Null values in dataset using stats method

data.isnull().sum()

# checking Null values in dataset using graphical method

data.isnull().sum().plot(kind = 'bar')
plt.title('The plot shows Null values present in columns')
plt.show()

data

# data.iloc[row_index,column_index]
data.iloc[2,2]

# data filter
data[data['UK'] > 300]

df = pd.DataFrame({'Gender':['Male','Female','Male','Female'],
                   'Station':['Thane', 'Bhandup','Kalyan','Diva'],
                   'Age': [50,70,90,45],
                   'Salary':[1000,3000,5000,7000]})
df

male_data = df[df['Gender'] == 'Male']
male_data

female_data = df[df['Gender'] == 'Female']
female_data

df['Gender'].value_counts().plot(kind = 'pie', autopct = '%0.2f',explode = [0.015,0.015])

plt.title('gender Distribution')
plt.show()

# lecture 2

import numpy as np
import pandas as pd

df = pd.DataFrame({
    'Name':['A','B','C','D','E','F'],
    'Department':['HR','IT','SALES','HR','IT','SALES'],
    'Age':[21,23,34,56,57,43],
    'salary':[3000,4000,5000,6000,7000,8000],
    'Experience_years':[1,3,1,2,5,6]})
df

# Descriptive Stats : Method 1
df.describe()

# ********Descriptive Stats : Method 2
from collections import OrderedDict

stats = []

for i in df.select_dtypes(exclude= 'object'):

  numerical_stats = OrderedDict({
        'Feature' : i,
        'count' : df[i].count(),
        'Maximum': df[i].max(),
        'Minimum': df[i].min(),
        'Mean': df[i].mean(),
        'Median': df[i].median(),
        'Q1':df[i].quantile(0.25),
        'Q3':df[i].quantile(0.75),
        'IQR': df[i].quantile(0.75) - df[i].quantile(0.25),
        'LW': df[i].quantile(0.25) - 1.5 * df[i].quantile(0.75) - df[i].quantile(0.25),
        'UW': df[i].quantile(0.25) + 1.5 * df[i].quantile(0.75) - df[i].quantile(0.25),
        'Standard Deviation': df[i].std(),
        'Skewness':df[i].skew(),
        'Kurtosis':df[i].kurt()
  })
  stats.append(numerical_stats)
  report = pd.DataFrame(stats)

report.T

df = pd.DataFrame({
    'Name':['A','B',np.nan,'D',np.nan,'F'],
    'Department':['HR',np.nan,'SALES',np.nan,'IT','SALES'],
    'Age':[21,23,34,56,57,43],
    'salary':[3000,4000,5000,6000,np.nan,8000],
    'Experience_years':[1,3,np.nan,2,5,6]})
df.isnull().sum()

import matplotlib.pyplot as plt

df.isnull().sum().plot(kind = 'bar',color = 'c')
plt.title('Graph showing missing values information')
plt.show()

# Imputation Stats
df

# df ['salary'] = df['salary'].fillna(median of salary)
df ['salary'] = df['salary'].fillna(df['salary'].median())

df['Experience_years'] = df['Experience_years'].fillna(df['Experience_years'].median())

df['Department'] = df['Department'].fillna(df['Department'].mode()[0])

df['Name'] = df['Name'].fillna(df['X'])

import pandas as pd
import numpy as np


employee_data = {
    'Employee_ID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Name': ['Amit', 'Priya', 'Rahul', 'Sneha', 'Karan', 'Neha', 'Vijay', 'Pooja', 'Rohit', 'Anjali'],
    'Age': [25, 30, np.nan, 28, 35, np.nan, 40, 29, 31, 27],
    'Department': ['HR', 'IT', 'Finance', np.nan, 'IT', 'HR', 'Finance', 'Marketing', np.nan, 'IT'],
    'Salary': [45000, 60000, 55000, np.nan, 70000, 48000, np.nan, 52000, 61000, 58000],
    'Experience': [2, 5, 4, 3, np.nan, 2, 10, 4, 6, np.nan],
    'Performance_Rating': [4.5, 4.8, np.nan, 4.2, 4.9, 4.1, 5.0, np.nan, 4.6, 4.3]
}


df = pd.DataFrame(employee_data)

df

# checking the information

df.info()

from collections import OrderedDict

stats = []

for i in df.select_dtypes(exclude= 'object'):

  numerical_stats = OrderedDict({
        'Feature' : i,
        'count' : df[i].count(),
        'Maximum': df[i].max(),
        'Minimum': df[i].min(),
        'Mean': df[i].mean(),
        'Median': df[i].median(),
        'Q1':df[i].quantile(0.25),
        'Q3':df[i].quantile(0.75),
        'IQR': df[i].quantile(0.75) - df[i].quantile(0.25),
        'LW': df[i].quantile(0.25) - 1.5 * df[i].quantile(0.75) - df[i].quantile(0.25),
        'UW': df[i].quantile(0.25) + 1.5 * df[i].quantile(0.75) - df[i].quantile(0.25),
        'Standard Deviation': df[i].std(),
        'Skewness':df[i].skew(),
        'Kurtosis':df[i].kurt()
  })
  stats.append(numerical_stats)
  report = pd.DataFrame(stats)

report.T

from collections import OrderedDict

stats = []

for i in df.select_dtypes(include= 'object'):
  numerical_stats = OrderedDict({
      'feature': i,
      'count':df[i].count(),
      'mode': df[i].mode()[0]
  })
  stats.append(numerical_stats)
  report=pd.DataFrame(stats)
report.T

import matplotlib.pyplot as plt

df.isnull().sum().plot(kind = 'bar',color = 'c')
plt.title('Graph showing missing values information')
plt.show()

df

df['Age'] = df['Age'].fillna(df['Age'].median())
df['Department'] = df['Department'].fillna(df['Department'].mode()[0])
df['Salary'] = df['Salary'].fillna(df['Salary'].median())
df['Experience'] = df['Experience'].fillna(df['Experience'].median())
df['Performance_Rating'] = df['Performance_Rating'].fillna(df['Performance_Rating'].median())
df

df[df['Department'] == 'HR']

df[df['Name']== 'Pooja']

df[df['Department'] == 'Finance']

# lecture3 Case Study (Titanic Dataset)

# importing data manipulation library
import numpy as np
import pandas as pd

# Data Ingestion

df = pd.read_csv('/content/titanic_dataset.csv')
df

# checking dataset information
df.info()

# checking duplicate entries in dataset
df.duplicated().sum()

# Checking Descriptive Statistics

from collections import OrderedDict

stats = []

for i in df.select_dtypes(exclude= 'object'):
  numerical_stats = OrderedDict({
        'Feature' : i,
        'count' : df[i].count(),
        'Maximum': df[i].max(),
        'Minimum': df[i].min(),
        'Mean': df[i].mean(),
        'Median': df[i].median(),
        'Q1':df[i].quantile(0.25),
        'Q3':df[i].quantile(0.75),
        'IQR': df[i].quantile(0.75) - df[i].quantile(0.25),
        'LW': df[i].quantile(0.25) - 1.5 * df[i].quantile(0.75) - df[i].quantile(0.25),
        'UW': df[i].quantile(0.25) + 1.5 * df[i].quantile(0.75) - df[i].quantile(0.25),
        'Standard Deviation': df[i].std(),
        'Skewness':df[i].skew(),
        'Kurtosis':df[i].kurt()

  })
  stats.append(numerical_stats)
  report = pd.DataFrame(stats)

print(report)

# ***Descriptive Stats on Categorical column

df.describe(include= 'object')

# calculate the percentage of people who boarded embarked from Southhampton
# value_counts() is used for displaying dat
df['Embarked'].value_counts().plot(kind = 'pie',
                                         autopct = '%0.2f',
                                         explode = [0.01,0.01,0.01])

# calculate percenatage gender distribution

df['Sex'].value_counts().plot(kind = 'pie',
                                    autopct = '%0.2f',
                                    explode = [0.01,0.01])

# checking percentage survived distribution stats

df['Survived'].value_counts().plot(kind = 'pie',
                                   autopct = '%0.2f',
                                   explode = [0.01,0.01])

# we converting the seperate data into different csv file for Southhampton

south_hampton = df[df['Embarked'] == 'S']
south_hampton.to_csv('South_hampton.csv')

import matplotlib.pyplot as plt

south_hampton['Survived'].value_counts().plot(kind = 'pie',
                                              autopct ='%0.2f',
                                              explode = [0.01,0.01])
plt.title('distribution of people survived in Southhampton')

south_hampton['Pclass'].value_counts().plot(kind='pie',
                                            autopct = '%0.2f',
                                            explode = [0.02,0.02,0.02])

south_hampton_survived = south_hampton[(south_hampton['Pclass'] == 3) & (south_hampton['Survived']== 1)]
south_hampton_survived

south_hampton_non_survived = south_hampton[(south_hampton['Pclass'] == 3) & (south_hampton['Survived']== 0)]
south_hampton_non_survived

south_hampton_survived['Sex'].value_counts()

south_hampton_non_survived['Sex'].value_counts()

# we converting the seperate data into different csv file for Cherburg

Cherburg = df[df['Embarked'] == 'C']
Cherburg.to_csv('Cherburg.csv')

Cherburg['Survived'].value_counts().plot(kind = 'pie',
                                         autopct = '%0.2f',
                                         explode = [0.01,0.01])

Cherburg['Pclass'].value_counts()

Cherburg_survived = Cherburg[(Cherburg['Pclass'] == 2) & (Cherburg['Survived']== 1)]
Cherburg_survived

Cherburg_non_survived = Cherburg[(Cherburg['Pclass'] == 2) & (Cherburg['Survived']== 0)]
Cherburg_non_survived

Cherburg_survived['Sex'].value_counts()

Cherburg_non_survived['Sex'].value_counts()

# we converting the seperate data into different csv file for Queenstown

Queenstown = df[df['Embarked'] == 'Q']
Queenstown.to_csv('Queenstown.csv')

Queenstown['Survived'].value_counts().plot(kind = 'pie',
                                           autopct = '%0.2f',
                                           explode = [0.01,0.01])

Queenstown['Pclass'].value_counts()

Queenstown_survived = Queenstown[(Queenstown['Pclass'] == 1) & (Queenstown['Survived']== 1)]
Queenstown_survived

Queenstown_non_survived = Queenstown[(Queenstown['Pclass'] == 1) & (Queenstown['Survived']== 0)]
Queenstown_non_survived

Queenstown_survived['Sex'].value_counts()

Queenstown_non_survived['Sex'].value_counts()

# Another depth analysis (crosstab)
# margin give total vertically and horizontally

pd.crosstab(index = df['Sex'],columns = [df['Survived'],df['Pclass']],margins= True)

pd.crosstab(index = df['Sex'],columns = df['Survived']).plot(kind = 'bar')

