# -*- coding: utf-8 -*-
"""EDA_Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LRnCAwYJbKkdRPASwdEbEDefGOnauMMn
"""

# Import data manipulation libraries
import numpy as np
import pandas as pd

# import data visualization libraries
import matplotlib.pyplot as plt
import seaborn as sns

# import logging
import logging
logging.basicConfig(level = logging.INFO,
                    filemode = 'w',
                    filename = 'model.log',
                    format = '%(asctime)s - %(message)s',
                    force = True)

logging.info('EDA Process started')

try:
  df = pd.read_csv('/content/titanic_dataset.csv')
except:
  print('File not found')

df.sample(frac = 1)

# Checking Dataset information
df.info()

# Missing Values Information using Graphical Method
df.isnull().sum().plot(kind = 'barh',color = 'lightgray',edgecolor = 'k')
plt.xlabel('Missing Values')
plt.ylabel('Data columns')
plt.title('Missing Values Information')
plt.show()

# checking duplicate records  present in dataset
df.duplicated().sum()

# segregate categorical Data and numerical data
categorical_data = df.select_dtypes(include = ['object'])
categorical_data

numerical_data = df.select_dtypes(exclude='object')
numerical_data

"""#******** higher the feature lower will be the ML model prediction"""

# Checking Descriptive Stats using ordereddict function

from collections import OrderedDict
stats = []

for i in numerical_data.columns:
  numerical_stats = OrderedDict({
      'Feature':i,
      'Skewness':numerical_data[i].skew(),
      'Kurtosis':numerical_data[i].kurt(),
      'Mean':numerical_data[i].mean(),
      'Median':numerical_data[i].median(),
      'Mode':numerical_data[i].mode()[0],
      'Standard Deviation':numerical_data[i].std(),
      'Variance':numerical_data[i].var(),
      'Minimum':numerical_data[i].min(),
      'Maximum':numerical_data[i].max(),
      'Range':numerical_data[i].max()-numerical_data[i].min(),
      'IQR':numerical_data[i].quantile(0.75)-numerical_data[i].quantile(0.25),
      '1.5 IQR':1.5*(numerical_data[i].quantile(0.75)-numerical_data[i].quantile(0.25)),
      'Lower Fence':numerical_data[i].quantile(0.25)-1.5*(numerical_data[i].quantile(0.75)-numerical_data[i].quantile(0.25)),
      'Upper Fence':numerical_data[i].quantile(0.75)+1.5*(numerical_data[i].quantile(0.75)-numerical_data[i].quantile(0.25))


  })
  stats.append(numerical_stats)
stats_df = pd.DataFrame(stats)
stats_df

df.describe(include= 'object')

"""<!-- Observations -->
1. The Dataset contains 10000 rows and 20 columns
2. out of 20 columns 09 best features selected based on domain knowledge
  - Sex, Embarked, Pclass, Age, SibSp, Parch, FamilySize, Isalone and survived
3. Considering sex and Embarked both are Nominal Data so we can encode with labelEncoding i.e. Converting categorical data into numerical.
4. Based on numerical desciptive stats it was observed that all numerical columns are showing non-normal distribution
"""

# Using groupby function

df.groupby(['Sex','Survived'])['Survived'].count()

df.groupby('Sex')['Age'].mean()

df.groupby('Sex')['Fare'].mean()

pd.crosstab(index= [df['Sex'],df['Survived']],columns= [df['Pclass'],
            df['Embarked']],margins= True)

plt.figure(figsize = (10,30))
pd.crosstab(index= [df['Sex'],df['Survived']],columns= [df['Pclass'],
            df['Embarked']]).plot(kind = 'bar')
plt.legend(loc = 'best')
plt.show()


"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VY8manjNoYJWIjAw2MolU9IPpEdzelvL
"""

sns.barplot(data = df,x = 'Survived', y = 'Sex')

sns.scatterplot(data = df,x = 'Age', y = 'Survived', hue = 'Embarked')

fig,ax = plt.subplots(3,3, figsize = (10,10))
sns.scatterplot(data = df,x = 'Age', y = 'Survived',hue = 'Embarked' ,ax = ax[0][0])
sns.scatterplot(data = df,x = 'Age', y = 'Survived',hue = 'Pclass' ,ax = ax[0][1])
sns.scatterplot(data = df,x = 'Age', y = 'Survived',hue = 'Sex' ,ax = ax[1][0])
sns.scatterplot(data = df,x = 'Age', y = 'Survived',hue = 'IsAlone' ,ax = ax[1][1])
sns.scatterplot(data = df,x = 'Age', y = 'Survived',hue = 'FamilySize' ,ax = ax[2][0])
sns.countplot(data = df,x = 'Survived', hue = 'Sex' ,ax = ax[2][1])
sns.boxplot(data = df,x = 'Survived', y = 'Age',hue = 'Sex' ,ax = ax[2][2])
sns.jointplot(data = df , x = 'Age' , y = 'Survived',ax = ax[2][1])
plt.tight_layout()
plt.show()

sns.pairplot(data =df)

# Drop unwanted columns
df.columns

# Data Cleaning

df.drop(columns = ['PassengerId', 'Name',
       'Ticket', 'Fare', 'Cabin', 'Nationality', 'Occupation',
        'Deck', 'Title', 'AgeGroup', 'TravelPurpose',
       ],axis = 1,inplace= True)

df

# if we want to use onehot encoder always use it with PCA to reduce the dimension (dimension = columns)
 '''
 Two types of encoding:
    1.Ordinal encoding
    2.Label encoding
 '''

# Converting Categorical Data Into Numerical Data

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

for i in df.select_dtypes(include= 'object'):
  df[i] = le.fit_transform(df[i])

df

plt.figure(figsize=(10,10))
sns.heatmap(data = df.corr())

# desc stats of data
# use subplots
# use hue conditions for columns such as economy, rating, price